# Generated by Django 5.0.1 on 2024-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Active"), (2, "Inactive")], default=1
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pre_approved_at", models.DateTimeField()),
            ],
            options={
                "db_table": "customers",
                "ordering": ["id"],
            },
        ),
    ]
